config/routes.rb
Rails.application.routes.draw do
  default_url_options protocol: :https

  get '/ping' => 'ping#index', :constraints => {ip: %r{127.0.0.1}}

  devise_for :administrations, skip: %i[password registrations]

  devise_for :administrateurs, controllers: {
    sessions: 'administrateurs/sessions'
  }, skip: %i[password registrations]

  devise_for :gestionnaires, controllers: {
    sessions: 'gestionnaires/sessions',
    passwords: 'gestionnaires/passwords'
  }, skip: [:registrations]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/users/sign_in/demo' => 'users/sessions#demo'
    get '/users/no_procedure' => 'users/sessions#no_procedure'
  end

  devise_scope :gestionnaire do
    get '/gestionnaires/sign_in/demo' => 'gestionnaires/sessions#demo'
    get '/gestionnaires/edit' => 'gestionnaires/registrations#edit', :as => 'edit_gestionnaires_registration'
    put '/gestionnaires' => 'gestionnaires/registrations#update', :as => 'gestionnaires_registration'
  end

  devise_scope :administrateur do
    get '/administrateurs/sign_in/demo' => 'administrateurs/sessions#demo'
  end

  root 'root#index'

  get 'cgu' => 'cgu#index'
  get 'demo' => 'demo#index'
  get 'users' => 'users#index'
  get 'admin' => 'admin#index'
  get 'backoffice' => 'backoffice#index'

  get 'simplifications' => 'opensimplif#index'
  get 'simplifications/reload_smartlisting' => 'opensimplif#reload_smartlisting'
  get 'simplifications/nothing' => 'opensimplif#nothing'
  get 'simplifications/:id' => 'opensimplif#index', as: :simplification

  resources :administrations

  namespace :france_connect do
    get 'particulier' => 'particulier#login'
    get 'particulier/callback' => 'particulier#callback'

    get 'particulier/new' => 'particulier#new'
    post 'particulier/create' => 'particulier#create'
    post 'particulier/check_email' => 'particulier#check_email'
  end

  namespace :users do
    namespace :dossiers do
      resources :invites, only: %i[index show]

      post '/commentaire' => 'commentaires#create'
    end

    resources :dossiers do
      get '/add_siret' => 'dossiers/add_siret#show'

      get '/description' => 'description#show'
      # get '/description/error' => 'description#error'
      post 'description' => 'description#create'

      patch 'pieces_justificatives' => 'description#pieces_justificatives'

      get '/recapitulatif' => 'recapitulatif#show'
      post '/recapitulatif/initiate' => 'recapitulatif#initiate'
      post '/recapitulatif/submit' => 'recapitulatif#submit'

      post '/commentaire' => 'commentaires#create'
      resources :commentaires, only: [:index]

      get '/carte/position' => 'carte#get_position'
      post '/carte/cadastre' => 'carte#get_cadastre'

      get '/carte' => 'carte#show'
      post '/carte' => 'carte#save'

      put '/archive' => 'dossiers#archive'

      post '/siret_informations' => 'dossiers#siret_informations'
      put '/change_siret' => 'dossiers#change_siret'
    end

    resource :dossiers
  end

  namespace :admin do
    get 'sign_in' => '/administrateurs/sessions#new'
    get 'procedures/archived' => 'procedures#archived'
    get 'procedures/draft' => 'procedures#draft'
    get 'procedures/path_list' => 'procedures#path_list'
    get 'profile' => 'profile#show', as: :profile

    get 'change_dossier_state' => 'change_dossier_state#index'
    post 'change_dossier_state' => 'change_dossier_state#check'
    patch 'change_dossier_state' => 'change_dossier_state#change'

    resources :procedures do
      resources :types_de_champ, only: [:destroy]
      resource :types_de_champ, only: %i[show update] do
        post '/:index/move_up' => 'types_de_champ#move_up', as: :move_up
        post '/:index/move_down' => 'types_de_champ#move_down', as: :move_down
      end

      resource :pieces_justificatives, only: %i[show update]
      resources :pieces_justificatives, only: :destroy
      resource :pieces_justificatives, only: %i[show update] do
        post '/:index/move_up' => 'pieces_justificatives#move_up', as: :move_up
        post '/:index/move_down' => 'pieces_justificatives#move_down', as: :move_down
      end

      resources 'mails'

      put 'archive' => 'procedures#archive', as: :archive
      put 'publish' => 'procedures#publish', as: :publish
      post 'transfer' => 'procedures#transfer', as: :transfer
      put 'clone' => 'procedures#clone', as: :clone

      resource :accompagnateurs, only: %i[show update]

      resource :previsualisation, only: [:show]
    end

    namespace :accompagnateurs do
      get 'show' # delete after fixed tests admin/accompagnateurs/show_spec without this line
    end

    resources :gestionnaires, only: %i[index create destroy]
  end

  namespace :ban do
    get 'search' => 'search#get'
    get 'address_point' => 'search#get_address_point'
  end

  namespace :invites do
    post 'dossier/:dossier_id' => '/invites#create', as: 'dossier'
  end

  namespace :backoffice do
    get 'sign_in' => '/gestionnaires/sessions#new'
    get 'dossiers/search' => 'dossiers#search'
    get 'download_dossiers' => 'dossiers#download_dossiers'

    resources :dossiers do
      post 'valid' => 'dossiers#valid'
      post 'receive' => 'dossiers#receive'
      post 'refuse' => 'dossiers#refuse'
      post 'without_continuation' => 'dossiers#without_continuation'
      post 'close' => 'dossiers#close'
      post 'archive' => 'dossiers#archive'

      put 'follow' => 'dossiers#follow'
      resources :commentaires, only: [:index]
    end

    namespace :dossiers do
      post 'filter'

      get 'procedure/:id' => 'procedure#index', as: 'procedure'
      post 'procedure/:id/filter' => 'procedure#filter', as: 'procedure_filter'
    end

    resources :commentaires, only: [:create]

    namespace :preference_list_dossier do
      post 'add'
      delete 'delete'

      get 'reload_smartlisting' => '/backoffice/dossiers#reload_smartlisting'
      get 'reload_pref_list'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :procedures, only: %i[index show] do
        resources :dossiers, only: %i[index show]
      end
    end

    namespace :statistiques do
      get 'dossiers' => '/api/statistiques#dossiers_stats'
    end
  end

  namespace :commencer do
    get '/:procedure_path' => '/users/dossiers#commencer'
  end

  apipie

  mount ActionCable.server => '/cable'
end

app/controllers/api/v1/dossiers_controller.rb
class API::V1::DossiersController < APIController
  api :GET, '/procedures/:procedure_id/dossiers/', 'Liste de tous les dossiers d\'une procédure'
  param :procedure_id, Integer, desc: "L'identifiant de la procédure", required: true
  param :token, String, desc: 'Token administrateur', required: true
  error code: 401, desc: 'Non autorisé'
  error code: 404, desc: 'Procédure inconnue'

  description <<-EOS
  Plop
  EOS

  meta champs: {
  }

  def index
    procedure = current_administrateur.procedures.find(params[:procedure_id])
    dossiers = procedure.dossiers.where.not(state: :draft).paginate(page: params[:page])

    render json: {dossiers: dossiers.map { |dossier| DossiersSerializer.new(dossier) }, pagination: pagination(dossiers)}, status: 200
  rescue ActiveRecord::RecordNotFound
    render json: {}, status: 404
  end

  api :GET, '/procedures/:procedure_id/dossiers/:id', 'Informations du dossier d\'une procédure'
  param :procedure_id, Integer, desc: "L'identifiant de la procédure", required: true
  param :dossier_id, Integer, desc: "L'identifiant du dossier", required: true
  param :token, String, desc: 'Token administrateur', required: true
  error code: 401, desc: 'Non autorisé'
  error code: 404, desc: 'Procédure ou dossier inconnu'

  description <<-EOS
  Plop
  EOS

  meta champs: {

  }

  def show
    procedure = current_administrateur.procedures.find(params[:procedure_id])
    dossier = procedure.dossiers.find(params[:id])

    respond_to do |format|
      format.json { render json: {dossier: DossierSerializer.new(dossier).as_json}, status: 200 }
      format.csv { render csv: dossier.as_csv, status: 200 }
    end
  rescue ActiveRecord::RecordNotFound
    render json: {}, status: 404
  end

  def pagination(dossiers)
    {
      page: dossiers.current_page,
      resultats_par_page: dossiers.per_page,
      nombre_de_page: dossiers.total_pages
    }
  end
end

app/controllers/backoffice/commentaires_controller.rb
class Backoffice::CommentairesController < CommentairesController
  before_action :authenticate_gestionnaire!

  def gestionnaire?
    true
  end
end

app/controllers/backoffice/dossiers/procedure_controller.rb
class Backoffice::Dossiers::ProcedureController < Backoffice::DossiersListController
  def index
    super

    dossiers_list_facade.service.filter_procedure! params[:id]

    redirect_to simplifications_path
  rescue ActiveRecord::RecordNotFound
    flash.alert = "Cette procédure n'existe pas ou vous n'y avez pas accès."
    redirect_to simplifications_path
  end

  def filter
    super

    redirect_to simplification_path(id: params[:id])
  end

  private

  def retrieve_procedure
    Procedure.find params[:id]
  end
end

app/controllers/backoffice/dossiers_controller.rb
class Backoffice::DossiersController < Backoffice::DossiersListController
  respond_to :html, :xlsx, :ods, :csv

  def index
    procedure = current_gestionnaire.procedure_filter

    if procedure.nil?
      procedure_list = dossiers_list_facade.gestionnaire_procedures_name_and_id_list
      if procedure_list.count.zero?
        flash.alert = "Vous n'avez aucune procédure d'affectée."
        return redirect_to root_path
      end

      procedure = procedure_list.first[:id]
    end

    redirect_to backoffice_dossiers_procedure_path(id: procedure)
  end

  def show
    create_dossier_facade params[:id]

    Unread.where(gestionnaire: current_gestionnaire, dossier: params[:id]).delete_all
  end

  def filter
    super

    redirect_to backoffice_dossiers_path(liste: param_liste)
  end

  def download_dossiers
    dossiers = dossiers_list_facade(param_liste).dossiers_to_display
    if Procedure.find_by(id: params[:procedure_id])
      respond_with Dossier.export_full_generation(dossiers, request.format) unless dossiers.empty?
    else
      respond_to do |format|
        format.xlsx { render xlsx: dossiers }
        format.ods { render ods: dossiers }
        format.csv { render csv: dossiers }
      end
    end
  end

  def search
    @search_terms = params[:q]

    # full text search
    # unless @dossiers.any?
    #   @dossiers = Search.new(
    #     query: @search_terms,
    #     page: params[:page]
    #   ).results
    # end

    @dossiers = Dossier.not_archived.not_draft.search(@search_terms)
    @dossiers = Dossier.none if @dossiers.empty?

    smart_listing_create :search,
                         @dossiers,
                         partial: 'backoffice/dossiers/list',
                         array: true,
                         default_sort: dossiers_list_facade.service.default_sort
  rescue RuntimeError
    smart_listing_create :search,
                         [],
                         partial: 'backoffice/dossiers/list',
                         array: true,
                         default_sort: dossiers_list_facade.service.default_sort
  end

  def valid
    create_dossier_facade params[:dossier_id]

    @facade.dossier.next_step! 'gestionnaire', 'valid'
    flash.notice = 'Dossier confirmé avec succès.'

    # #NotificationMailer.dossier_validated(@facade.dossier).deliver_now!

    redirect_to backoffice_dossier_path(id: @facade.dossier.id)
  end

  def receive
    create_dossier_facade params[:dossier_id]

    @facade.dossier.next_step! 'gestionnaire', 'receive'
    flash.notice = 'Dossier considéré comme reçu.'

    # NotificationMailer.dossier_received(@facade.dossier).deliver_now!

    redirect_to backoffice_dossier_path(id: @facade.dossier.id)
  end

  def refuse
    create_dossier_facade params[:dossier_id]

    @facade.dossier.next_step! 'gestionnaire', 'refuse'
    flash.notice = 'Dossier considéré comme refusé.'

    # NotificationMailer.dossier_refused(@facade.dossier).deliver_now!

    redirect_to backoffice_dossier_path(id: @facade.dossier.id)
  end

  def without_continuation
    create_dossier_facade params[:dossier_id]

    @facade.dossier.next_step! 'gestionnaire', 'without_continuation'
    flash.notice = 'Dossier considéré comme sans suite.'

    # NotificationMailer.dossier_without_continuation(@facade.dossier).deliver_now!

    redirect_to backoffice_dossier_path(id: @facade.dossier.id)
  end

  def close
    create_dossier_facade params[:dossier_id]

    @facade.dossier.next_step! 'gestionnaire', 'close'
    flash.notice = 'Dossier traité avec succès.'

    # NotificationMailer.dossier_closed(@facade.dossier).deliver_now!

    redirect_to backoffice_dossier_path(id: @facade.dossier.id)
  end

  def follow
    follow = current_gestionnaire.toggle_follow_dossier params[:dossier_id]

    Dossier.find(params[:dossier_id]).next_step! 'gestionnaire', 'follow'

    flash.notice = 'Simplification suivie' if follow.class == Follow
    redirect_to request.referer
  end

  def reload_smartlisting
    begin
      @liste = URI(request.referer).query.split('=').second
    rescue NoMethodError
      @liste = cookies[:liste] || 'all_state'
    end

    smartlisting_dossier

    render 'backoffice/dossiers/index', formats: :js
  end

  def archive
    facade = create_dossier_facade params[:dossier_id]
    unless facade.dossier.archived
      facade.dossier.update(archived: true)
      flash.notice = 'Dossier archivé'
    end
    redirect_to backoffice_dossiers_path
  end

  private

  def create_dossier_facade(dossier_id)
    @facade = DossierFacades.new dossier_id, current_gestionnaire.email
  rescue ActiveRecord::RecordNotFound
    flash.alert = t('errors.messages.dossier_not_found')
    redirect_to url_for(controller: '/backoffice')
  end

  def retrieve_procedure
    return if params[:procedure_id].blank?
    current_gestionnaire.procedures.find params[:procedure_id]
  end
end

app/controllers/backoffice/dossiers_list_controller.rb
class Backoffice::DossiersListController < ApplicationController
  include SmartListing::Helper::ControllerExtensions
  helper SmartListing::Helper

  before_action :authenticate_gestionnaire!

  def index
    cookies[:liste] = param_liste

    unless DossiersListGestionnaireService.dossiers_liste_libelle.include?(param_liste)
      cookies[:liste] = 'all_state'
    end

    dossiers_list_facade param_liste
    dossiers_list_facade.service.change_sort! param_sort unless param_smart_listing.nil?
    dossiers_list_facade.service.change_page! param_page

    smartlisting_dossier
  end

  def filter
    dossiers_list_facade param_liste
    dossiers_list_facade.service.add_filter param_filter
  end

  def dossiers_list_facade(liste = 'all_state')
    @facade_data_view ||= DossiersListFacades.new current_gestionnaire, liste, retrieve_procedure
  end

  def smartlisting_dossier(_dossiers_list = nil, liste = 'all_state')
    dossiers_list_facade liste

    new_dossiers_list = dossiers_list_facade.service.nouveaux
    follow_dossiers_list = dossiers_list_facade.service.suivi
    all_state_dossiers_list = dossiers_list_facade.service.all_state

    if param_page.nil?
      params[:dossiers_smart_listing] = {page: dossiers_list_facade.service.default_page}
    end

    smart_listing_create :new_dossiers,
                         new_dossiers_list,
                         partial: 'backoffice/dossiers/list',
                         array: true,
                         default_sort: dossiers_list_facade.service.default_sort

    smart_listing_create :follow_dossiers,
                         follow_dossiers_list,
                         partial: 'backoffice/dossiers/list',
                         array: true,
                         default_sort: dossiers_list_facade.service.default_sort

    smart_listing_create :all_state_dossiers,
                         all_state_dossiers_list,
                         partial: 'backoffice/dossiers/list',
                         array: true,
                         default_sort: dossiers_list_facade.service.default_sort
  end

  private

  def param_smart_listing
    params[:dossiers_smart_listing]
  end

  def param_page
    unless param_smart_listing.nil?
      return 1 if params[:dossiers_smart_listing][:page].blank?
      params[:dossiers_smart_listing][:page]
    end
  end

  def param_sort
    params[:dossiers_smart_listing][:sort] unless param_smart_listing.nil?
  end

  def param_filter
    params[:filter_input]
  end

  def param_liste
    @liste ||= params[:liste] || cookies[:liste] || 'all_state'
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  def index
    if !gestionnaire_signed_in?
      redirect_to(controller: '/gestionnaires/sessions', action: :new)
    else
      redirect_to(:backoffice_dossiers)
    end
  end
end

app/controllers/users/dossiers/add_siret_controller.rb
class Users::Dossiers::AddSiretController < ApplicationController
  def show
    @facade = DossierFacades.new params[:dossier_id], current_user.email

    raise ActiveRecord::RecordNotFound unless @facade.procedure.individual_with_siret?

    @siret = current_user.siret unless current_user.siret.nil?
  rescue ActiveRecord::RecordNotFound
    flash.alert = t('errors.messages.dossier_not_found')
    redirect_to users_dossiers_path
  end
end

app/controllers/users/dossiers/commentaires_controller.rb
class Users::Dossiers::CommentairesController < CommentairesController
  before_action :authenticate_user!
end

app/views/backoffice/dossiers/_filter_framed.html.haml
%div.filter_framed.panel.panel-primary{id: "#{filter_framed_id}", style:'width: 300px; height: 100px; position: absolute; top: 0; left: 0; display: none'}
  .panel-heading
    = preference.libelle

  =form_tag @facade_data_view.filter_url, {class: 'panel-body form-inline', method: :post} do
    %input.form-control.filter_input{name: "filter_input[#{preference.table_attr}]", style:'width: 69%', value: "#{preference.filter}"}
    %button.btn.btn-sm.btn-success
      %i.fa.fa-check
    %div.btn.btn-sm.btn-danger.erase-filter
      %i.fa.fa-remove

app/views/backoffice/dossiers/_followers.html.haml
%h3
  =t('dynamics.dossiers.followers.title')

%br
.row
  .col-md-4.col-sm-4.col-xs-4.col-lg-4
    - if @facade.followers.size > 0
      %ul
        - @facade.followers.each do |follower|
          %li
            = follower.email
    - else
      Aucune personne ne suit ce dossier

app/views/backoffice/dossiers/_list.html.haml
%table#dossiers_list.table
  %thead
    %tr
      - if smart_listing.name.to_s == 'follow_dossiers' || smart_listing.name.to_s == 'mes_dossiers'
        %th.col-md-1.col-lg-1.col-sm-1.col-xs-1.col-sm-1.col-xs-1.center
          %i.fa.fa-bell

      - @facade_data_view.preference_list_dossiers_filter.each do |preference|
        - unless preference.libelle == 'Statut' || preference.libelle == 'État'
          %th{class: "col-md-#{preference.bootstrap_lg} col-lg-#{preference.bootstrap_lg}"}
            - if preference.table.to_s.include? 'champs'
              = preference.libelle
            - else
              = smart_listing.sortable preference.libelle, preference.table_attr
            - if @facade_data_view.active_filter? preference
              %i.filter.fa.fa-filter{style: "color:#{(preference.filter.blank? ? 'grey' : 'orange')}", id: "filter_#{smart_listing.name.to_s}_#{preference.table_attr.sub('.', '_')}"}
              = render partial: 'backoffice/dossiers/filter_framed', locals:{preference: preference, filter_framed_id: "framed_filter_#{smart_listing.name.to_s}_#{preference.table_attr.sub('.', '_')}"}

      %th.col-md-1.col-lg-1.col-sm-1.col-xs-1.col-sm-1.col-xs-1.center Actions
      %th.col-md-1.col-lg-1.col-sm-1.col-xs-1.col-sm-1.col-xs-1.center Abonnés

  - unless smart_listing.empty?
    - smart_listing.collection.each do |dossier|
      %tr.dossier-row{id: "tr_dossier_#{dossier.id}", 'data-dossier_url' => backoffice_dossier_url(id: dossier.id)}
        - if smart_listing.name.to_s == 'follow_dossiers' || smart_listing.name.to_s == 'mes_dossiers'
          %td.col-md-1.col-lg-1.col-sm-1.col-xs-1.col-sm-1.col-xs-1.center
            - total_notif = dossier.unreads.where(gestionnaire: current_gestionnaire).count
            - if total_notif == 0
              .badge.progress-bar-default
                = total_notif
            - else
              .badge.progress-bar-warning
                = total_notif
        - @facade_data_view.preference_list_dossiers_filter.each_with_index do |preference, index|
          - unless preference.libelle == 'Statut' || preference.libelle == 'État'
            %td
              - if preference.table.nil? || preference.table.empty?
                - value = dossier.decorate.public_send(preference.attr_decorate)
              - elsif preference.table == 'champs'
                - value = dossier.champs.find_by_type_de_champ_id(preference.attr).value rescue nil
              - else
                - begin
                  - value = dossier.public_send(preference.table).decorate.public_send(preference.attr_decorate)
                - rescue NoMethodError
                  - value = ''

              = value

        %td.center
          - if current_gestionnaire.follow?(dossier.id)
            = link_to('Quitter'.html_safe, backoffice_dossier_follow_path(dossier_id: dossier.id), 'data-method' => :put, class: 'btn-sm btn-danger', id: "suivre_dossier_#{dossier.id}")
          - else
            = link_to('Suivre', backoffice_dossier_follow_path(dossier_id: dossier.id), 'data-method' => :put, class: 'btn-sm btn-primary', id: "suivre_dossier_#{dossier.id}")
        %td.center{style:"color: #{dossier.total_follow == 0 ? 'red' : ''}"}
          = dossier.total_follow

= smart_listing.paginate
- if smart_listing.name.to_s == 'follow_dossiers' && smart_listing.collection.count > 0
  = smart_listing.pagination_per_page_links
  %br


- if smart_listing.empty?
  %h4.center
    Aucun dossier

app/views/backoffice/dossiers/_pref_list.html.haml
%button#pref_list_dossier_close_action.btn.btn-danger.btn-xs.fixed-right
  %i.fa.fa-close
%h3
  =t('dynamics.backoffice.pref_list.title')

%p{style:'margin-top: 15px; margin-bottom: 20px'}
  =t('dynamics.backoffice.pref_list.description')

%h4.text-primary
  Actuelles

%ul
  - @facade_data_view.preference_list_dossiers_filter.each_with_index do |preference, index|
    %li
      = form_tag backoffice_preference_list_dossier_delete_path, method: :delete, remote: true  do
        = hidden_field_tag :pref_id, preference.id
        = hidden_field_tag :procedure_id, preference.procedure_id
        = preference.libelle
        %button.btn.btn-default.btn-xs{type: :submit, id: "delete_pref_list_#{preference[:table]}_#{preference[:attr]}"}
          %i.fa.fa-minus

%h4.text-success{style:'margin-top: 15px'}
  Disponibles

%table
  - PreferenceListDossier.available_columns_for(@facade_data_view.procedure_id).each_slice(2) do |two_tables|
    %tr
      - two_tables.each do |table|
        %td.col-sm-5.col-md-5.col-sm-5.col-xs-5.col-lg-5{style: 'vertical-align: top', colspan: (table.first == :champs ? 2 : 1)}
          %h5= table.first.to_s.gsub('_', ' ').capitalize
          %ul
            - if table.second
              - table.second.each do |columns|
                %li
                  = form_tag backoffice_preference_list_dossier_add_path, method: :post, remote: true do
                    = hidden_field_tag :libelle, columns.second[:libelle]
                    = hidden_field_tag :table, columns.second[:table]
                    = hidden_field_tag :attr, columns.second[:attr]
                    = hidden_field_tag :attr_decorate, columns.second[:attr_decorate]
                    = hidden_field_tag :bootstrap_lg, columns.second[:bootstrap_lg]
                    = hidden_field_tag :procedure_id, @facade_data_view.procedure_id
    
                    = columns.second[:libelle]
                    %button.btn.btn-default.btn-xs{type: :submit, id: "add_pref_list_#{columns.second[:table]}_#{columns.second[:attr]}"}
                      %i.fa.fa-plus

app/views/backoffice/dossiers/_pref_list.js.erb
$.ajax({
    method: 'get',
    url: '/backoffice/preference_list_dossier/reload_smartlisting?procedure_id=<%= @procedure_id %>',
    async: true
});

$.ajax({
    methd: 'get',
    url: '/backoffice/preference_list_dossier/reload_pref_list?procedure_id=<%= @procedure_id %>',
    async: true
}).done(function (data) {
    $("#pref_list_menu").html(data);
    pref_list_dossier_actions();
});

app/views/backoffice/dossiers/_state_description.html.haml
#state_description.row{style:'width: 50%; margin-left: auto; margin-right: auto'}
  .panel.panel-info
    .panel-body.center
      .row
        .col-md-1.col-lg-1.col-sm-1.col-xs-1.col-sm-1.col-xs-1
          .fa.fa-info-circle.text-info{style:'font-size: 2em; margin-top: 20%'}
        .col-md-11.col-sm-11.col-xs-11.col-lg-11
          - if dossiers_list_facade.liste == 'nouveaux'
            Tous les dossiers présents dans cette liste sont ceux qui
            %b
              n'ont jamais été ouvert par votre service.
            Il attende une première lecture et intervention de votre part.
          - elsif dossiers_list_facade.liste == 'a_traiter'
            Tous les dossiers présents dans cette liste sont ceux qui sont
            %b
              en cours de construction avec l'usager.
            Ils ne sont pas figés et ne sont donc pas complets.
          - elsif dossiers_list_facade.liste == 'fige'
            Tous les dossiers présents dans cette liste ont été déclarés
            %b
              complets
            et ne sont
            %b
              plus modifiables par l'usager.
            Ils attendent donc leurs dépots officiels qui doit être effectué par l'usager.
          - elsif dossiers_list_facade.liste == 'deposes'
            Tous les dossiers présents dans cette liste ont été
            %b
              officiellement déposé par l'usager pour examen.
            Il faut donc que vous confirmiez par "accusé de réception" la bonne réception de toutes les informations et documents demandés avant examen final.
          - elsif dossiers_list_facade.liste == 'a_instruire'
            Tous les dossiers présents dans cette liste sont à instruire. Ceux sont tous les dossiers
            %b
              qui ont reçu bonne réception.
          - elsif dossiers_list_facade.liste == 'termine'
            Tous les dossiers présents dans cette liste sont considérés comme cloturé car ils ont tous reçu un verdict final qui peut être "Validé", "Refusé" ou "Sans suite".

app/views/backoffice/dossiers/formulaire_private.js.erb
<% flash.each do |type, message| %>
$("#flash_message").html("<div class=\"alert alert-success move_up\" style=\"display: block:\"> <%= message.html_safe %></div>").children().fadeOut(5000)
<%  end %>
<% flash.clear %>

app/views/backoffice/dossiers/index.js.erb
<%= smart_listing_update :new_dossiers, {force: true} %>
<%= smart_listing_update :follow_dossiers, {force: true} %>
<%= smart_listing_update :all_state_dossiers, {force: true} %>

filters_init();
link_init();

app/views/backoffice/dossiers/search.js.erb
<%= smart_listing_update :search %>

filters_init();
link_init();

app/views/backoffice/dossiers/show.html.haml
%div.col-lg-12.col-md-12.col-sm-12.col-xs-12#backoffice_dossier_show
  = render partial: "dossiers/dossier_show"