config/routes.rb
Rails.application.routes.draw do
  default_url_options protocol: :https

  get '/ping' => 'ping#index', :constraints => {ip: %r{127.0.0.1}}

  devise_for :administrations, skip: %i[password registrations]

  devise_for :administrateurs, controllers: {
    sessions: 'administrateurs/sessions'
  }, skip: %i[password registrations]

  devise_for :gestionnaires, controllers: {
    sessions: 'gestionnaires/sessions',
    passwords: 'gestionnaires/passwords'
  }, skip: [:registrations]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    get '/users/sign_in/demo' => 'users/sessions#demo'
    get '/users/no_procedure' => 'users/sessions#no_procedure'
  end

  devise_scope :gestionnaire do
    get '/gestionnaires/sign_in/demo' => 'gestionnaires/sessions#demo'
    get '/gestionnaires/edit' => 'gestionnaires/registrations#edit', :as => 'edit_gestionnaires_registration'
    put '/gestionnaires' => 'gestionnaires/registrations#update', :as => 'gestionnaires_registration'
  end

  devise_scope :administrateur do
    get '/administrateurs/sign_in/demo' => 'administrateurs/sessions#demo'
  end

  root 'root#index'

  get 'cgu' => 'cgu#index'
  get 'demo' => 'demo#index'
  get 'users' => 'users#index'
  get 'admin' => 'admin#index'
  get 'backoffice' => 'backoffice#index'

  get 'simplifications' => 'opensimplif#index'
  get 'simplifications/reload_smartlisting' => 'opensimplif#reload_smartlisting'
  get 'simplifications/nothing' => 'opensimplif#nothing'
  get 'simplifications/:id' => 'opensimplif#index', as: :simplification

  resources :administrations

  namespace :france_connect do
    get 'particulier' => 'particulier#login'
    get 'particulier/callback' => 'particulier#callback'

    get 'particulier/new' => 'particulier#new'
    post 'particulier/create' => 'particulier#create'
    post 'particulier/check_email' => 'particulier#check_email'
  end

  namespace :users do
    namespace :dossiers do
      resources :invites, only: %i[index show]

      post '/commentaire' => 'commentaires#create'
    end

    resources :dossiers do
      get '/add_siret' => 'dossiers/add_siret#show'

      get '/description' => 'description#show'
      # get '/description/error' => 'description#error'
      post 'description' => 'description#create'

      patch 'pieces_justificatives' => 'description#pieces_justificatives'

      get '/recapitulatif' => 'recapitulatif#show'
      post '/recapitulatif/initiate' => 'recapitulatif#initiate'
      post '/recapitulatif/submit' => 'recapitulatif#submit'

      post '/commentaire' => 'commentaires#create'
      resources :commentaires, only: [:index]

      get '/carte/position' => 'carte#get_position'
      post '/carte/cadastre' => 'carte#get_cadastre'

      get '/carte' => 'carte#show'
      post '/carte' => 'carte#save'

      put '/archive' => 'dossiers#archive'

      post '/siret_informations' => 'dossiers#siret_informations'
      put '/change_siret' => 'dossiers#change_siret'
    end

    resource :dossiers
  end

  namespace :admin do
    get 'sign_in' => '/administrateurs/sessions#new'
    get 'procedures/archived' => 'procedures#archived'
    get 'procedures/draft' => 'procedures#draft'
    get 'procedures/path_list' => 'procedures#path_list'
    get 'profile' => 'profile#show', as: :profile

    get 'change_dossier_state' => 'change_dossier_state#index'
    post 'change_dossier_state' => 'change_dossier_state#check'
    patch 'change_dossier_state' => 'change_dossier_state#change'

    resources :procedures do
      resources :types_de_champ, only: [:destroy]
      resource :types_de_champ, only: %i[show update] do
        post '/:index/move_up' => 'types_de_champ#move_up', as: :move_up
        post '/:index/move_down' => 'types_de_champ#move_down', as: :move_down
      end

      resource :pieces_justificatives, only: %i[show update]
      resources :pieces_justificatives, only: :destroy
      resource :pieces_justificatives, only: %i[show update] do
        post '/:index/move_up' => 'pieces_justificatives#move_up', as: :move_up
        post '/:index/move_down' => 'pieces_justificatives#move_down', as: :move_down
      end

      resources 'mails'

      put 'archive' => 'procedures#archive', as: :archive
      put 'publish' => 'procedures#publish', as: :publish
      post 'transfer' => 'procedures#transfer', as: :transfer
      put 'clone' => 'procedures#clone', as: :clone

      resource :accompagnateurs, only: %i[show update]

      resource :previsualisation, only: [:show]
    end

    namespace :accompagnateurs do
      get 'show' # delete after fixed tests admin/accompagnateurs/show_spec without this line
    end

    resources :gestionnaires, only: %i[index create destroy]
  end

  namespace :ban do
    get 'search' => 'search#get'
    get 'address_point' => 'search#get_address_point'
  end

  namespace :invites do
    post 'dossier/:dossier_id' => '/invites#create', as: 'dossier'
  end

  namespace :backoffice do
    get 'sign_in' => '/gestionnaires/sessions#new'
    get 'dossiers/search' => 'dossiers#search'
    get 'download_dossiers' => 'dossiers#download_dossiers'

    resources :dossiers do
      post 'valid' => 'dossiers#valid'
      post 'receive' => 'dossiers#receive'
      post 'refuse' => 'dossiers#refuse'
      post 'without_continuation' => 'dossiers#without_continuation'
      post 'close' => 'dossiers#close'
      post 'archive' => 'dossiers#archive'

      put 'follow' => 'dossiers#follow'
      resources :commentaires, only: [:index]
    end

    namespace :dossiers do
      post 'filter'

      get 'procedure/:id' => 'procedure#index', as: 'procedure'
      post 'procedure/:id/filter' => 'procedure#filter', as: 'procedure_filter'
    end

    resources :commentaires, only: [:create]

    namespace :preference_list_dossier do
      post 'add'
      delete 'delete'

      get 'reload_smartlisting' => '/backoffice/dossiers#reload_smartlisting'
      get 'reload_pref_list'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :procedures, only: %i[index show] do
        resources :dossiers, only: %i[index show]
      end
    end

    namespace :statistiques do
      get 'dossiers' => '/api/statistiques#dossiers_stats'
    end
  end

  namespace :commencer do
    get '/:procedure_path' => '/users/dossiers#commencer'
  end

  apipie

  mount ActionCable.server => '/cable'
end

app/controllers/api/v1/dossiers_controller.rb
class API::V1::DossiersController < APIController
  api :GET, '/procedures/:procedure_id/dossiers/', 'Liste de tous les dossiers d\'une procédure'
  param :procedure_id, Integer, desc: "L'identifiant de la procédure", required: true
  param :token, String, desc: 'Token administrateur', required: true
  error code: 401, desc: 'Non autorisé'
  error code: 404, desc: 'Procédure inconnue'

  description <<-EOS
  Plop
  EOS

  meta champs: {
  }

  def index
    procedure = current_administrateur.procedures.find(params[:procedure_id])
    dossiers = procedure.dossiers.where.not(state: :draft).paginate(page: params[:page])

    render json: {dossiers: dossiers.map { |dossier| DossiersSerializer.new(dossier) }, pagination: pagination(dossiers)}, status: 200
  rescue ActiveRecord::RecordNotFound
    render json: {}, status: 404
  end

  api :GET, '/procedures/:procedure_id/dossiers/:id', 'Informations du dossier d\'une procédure'
  param :procedure_id, Integer, desc: "L'identifiant de la procédure", required: true
  param :dossier_id, Integer, desc: "L'identifiant du dossier", required: true
  param :token, String, desc: 'Token administrateur', required: true
  error code: 401, desc: 'Non autorisé'
  error code: 404, desc: 'Procédure ou dossier inconnu'

  description <<-EOS
  Plop
  EOS

  meta champs: {

  }

  def show
    procedure = current_administrateur.procedures.find(params[:procedure_id])
    dossier = procedure.dossiers.find(params[:id])

    respond_to do |format|
      format.json { render json: {dossier: DossierSerializer.new(dossier).as_json}, status: 200 }
      format.csv { render csv: dossier.as_csv, status: 200 }
    end
  rescue ActiveRecord::RecordNotFound
    render json: {}, status: 404
  end

  def pagination(dossiers)
    {
      page: dossiers.current_page,
      resultats_par_page: dossiers.per_page,
      nombre_de_page: dossiers.total_pages
    }
  end
end

app/controllers/backoffice/dossiers/procedure_controller.rb
class Backoffice::Dossiers::ProcedureController < Backoffice::DossiersListController
  def index
    super

    dossiers_list_facade.service.filter_procedure! params[:id]

    redirect_to simplifications_path
  rescue ActiveRecord::RecordNotFound
    flash.alert = "Cette procédure n'existe pas ou vous n'y avez pas accès."
    redirect_to simplifications_path
  end

  def filter
    super

    redirect_to simplification_path(id: params[:id])
  end

  private

  def retrieve_procedure
    Procedure.find params[:id]
  end
end

app/controllers/backoffice/dossiers_controller.rb
class Backoffice::DossiersController < Backoffice::DossiersListController
  respond_to :html, :xlsx, :ods, :csv

  def index
    procedure = current_gestionnaire.procedure_filter

    if procedure.nil?
      procedure_list = dossiers_list_facade.gestionnaire_procedures_name_and_id_list
      if procedure_list.count.zero?
        flash.alert = "Vous n'avez aucune procédure d'affectée."
        return redirect_to root_path
      end

      procedure = procedure_list.first[:id]
    end

    redirect_to backoffice_dossiers_procedure_path(id: procedure)
  end

  def show
    create_dossier_facade params[:id]

    Unread.where(gestionnaire: current_gestionnaire, dossier: params[:id]).delete_all
  end

  def filter
    super

    redirect_to backoffice_dossiers_path(liste: param_liste)
  end

  def download_dossiers
    dossiers = dossiers_list_facade(param_liste).dossiers_to_display
    if Procedure.find_by(id: params[:procedure_id])
      respond_with Dossier.export_full_generation(dossiers, request.format) unless dossiers.empty?
    else
      respond_to do |format|
        format.xlsx { render xlsx: dossiers }
        format.ods { render ods: dossiers }
        format.csv { render csv: dossiers }
      end
    end
  end

  def search
    @search_terms = params[:q]

    # full text search
    # unless @dossiers.any?
    #   @dossiers = Search.new(
    #     query: @search_terms,
    #     page: params[:page]
    #   ).results
    # end

    @dossiers = Dossier.not_archived.not_draft.search(@search_terms)
    @dossiers = Dossier.none if @dossiers.empty?

    smart_listing_create :search,
                         @dossiers,
                         partial: 'backoffice/dossiers/list',
                         array: true,
                         default_sort: dossiers_list_facade.service.default_sort
  rescue RuntimeError
    smart_listing_create :search,
                         [],
                         partial: 'backoffice/dossiers/list',
                         array: true,
                         default_sort: dossiers_list_facade.service.default_sort
  end

  def valid
    create_dossier_facade params[:dossier_id]

    @facade.dossier.next_step! 'gestionnaire', 'valid'
    flash.notice = 'Dossier confirmé avec succès.'

    # #NotificationMailer.dossier_validated(@facade.dossier).deliver_now!

    redirect_to backoffice_dossier_path(id: @facade.dossier.id)
  end

  def receive
    create_dossier_facade params[:dossier_id]

    @facade.dossier.next_step! 'gestionnaire', 'receive'
    flash.notice = 'Dossier considéré comme reçu.'

    # NotificationMailer.dossier_received(@facade.dossier).deliver_now!

    redirect_to backoffice_dossier_path(id: @facade.dossier.id)
  end

  def refuse
    create_dossier_facade params[:dossier_id]

    @facade.dossier.next_step! 'gestionnaire', 'refuse'
    flash.notice = 'Dossier considéré comme refusé.'

    # NotificationMailer.dossier_refused(@facade.dossier).deliver_now!

    redirect_to backoffice_dossier_path(id: @facade.dossier.id)
  end

  def without_continuation
    create_dossier_facade params[:dossier_id]

    @facade.dossier.next_step! 'gestionnaire', 'without_continuation'
    flash.notice = 'Dossier considéré comme sans suite.'

    # NotificationMailer.dossier_without_continuation(@facade.dossier).deliver_now!

    redirect_to backoffice_dossier_path(id: @facade.dossier.id)
  end

  def close
    create_dossier_facade params[:dossier_id]

    @facade.dossier.next_step! 'gestionnaire', 'close'
    flash.notice = 'Dossier traité avec succès.'

    # NotificationMailer.dossier_closed(@facade.dossier).deliver_now!

    redirect_to backoffice_dossier_path(id: @facade.dossier.id)
  end

  def follow
    follow = current_gestionnaire.toggle_follow_dossier params[:dossier_id]

    Dossier.find(params[:dossier_id]).next_step! 'gestionnaire', 'follow'

    flash.notice = 'Simplification suivie' if follow.class == Follow
    redirect_to request.referer
  end

  def reload_smartlisting
    begin
      @liste = URI(request.referer).query.split('=').second
    rescue NoMethodError
      @liste = cookies[:liste] || 'all_state'
    end

    smartlisting_dossier

    render 'backoffice/dossiers/index', formats: :js
  end

  def archive
    facade = create_dossier_facade params[:dossier_id]
    unless facade.dossier.archived
      facade.dossier.update(archived: true)
      flash.notice = 'Dossier archivé'
    end
    redirect_to backoffice_dossiers_path
  end

  private

  def create_dossier_facade(dossier_id)
    @facade = DossierFacades.new dossier_id, current_gestionnaire.email
  rescue ActiveRecord::RecordNotFound
    flash.alert = t('errors.messages.dossier_not_found')
    redirect_to url_for(controller: '/backoffice')
  end

  def retrieve_procedure
    return if params[:procedure_id].blank?
    current_gestionnaire.procedures.find params[:procedure_id]
  end
end

app/controllers/users/carte_controller.rb
class Users::CarteController < UsersController
  before_action only: [:show] do
    authorized_routes? self.class
  end

  def show
    @dossier = current_user_dossier
  rescue ActiveRecord::RecordNotFound
    flash.alert = t('errors.messages.dossier_not_found')
    redirect_to root_path
  end

  def save
    dossier = current_user_dossier

    dossier.cadastres.map(&:destroy)

    unless params[:json_latlngs].blank?
      ModuleApiCartoService.save_qp! dossier, params[:json_latlngs]
      ModuleApiCartoService.save_cadastre! dossier, params[:json_latlngs]
    end

    dossier.update_attributes(json_latlngs: params[:json_latlngs])

    controller = :recapitulatif
    controller = :description if dossier.draft?

    redirect_to url_for(controller: controller, action: :show, dossier_id: params[:dossier_id])
  end

  def get_position
    etablissement = current_user_dossier.etablissement
    point = Carto::Geocodeur.convert_adresse_to_point(etablissement.geo_adresse) unless etablissement.nil?

    lon = '2.428462'
    lat = '46.538192'
    zoom = '13'

    unless point.nil?
      lon = point.x.to_s
      lat = point.y.to_s
    end

    render json: {lon: lon, lat: lat, zoom: zoom, dossier_id: params[:dossier_id]}
  end

  def get_cadastre
    render json: {cadastres: ModuleApiCartoService.generate_cadastre(JSON.parse(params[:coordinates]))}
  end

  def self.route_authorization
    {
      states: %i[draft initiated replied updated],
      api_carto: true
    }
  end
end

app/controllers/users/commentaires_controller.rb
class Users::CommentairesController < CommentairesController
  before_action :authenticate_user!
end

app/controllers/users/dossiers/add_siret_controller.rb
class Users::Dossiers::AddSiretController < ApplicationController
  def show
    @facade = DossierFacades.new params[:dossier_id], current_user.email

    raise ActiveRecord::RecordNotFound unless @facade.procedure.individual_with_siret?

    @siret = current_user.siret unless current_user.siret.nil?
  rescue ActiveRecord::RecordNotFound
    flash.alert = t('errors.messages.dossier_not_found')
    redirect_to users_dossiers_path
  end
end

app/controllers/users/dossiers/commentaires_controller.rb
class Users::Dossiers::CommentairesController < CommentairesController
  before_action :authenticate_user!
end

app/controllers/users/dossiers/invites_controller.rb
class Users::Dossiers::InvitesController < UsersController
  def authenticate_user!
    session['user_return_to'] = request.fullpath
    return redirect_to new_user_registration_path(user_email: params[:email]) if !params[:email].blank? && User.find_by_email(params[:email]).nil?

    super
  end

  def show
    @facade = InviteDossierFacades.new params[:id].to_i, current_user.email

    render 'users/recapitulatif/show'
  rescue ActiveRecord::RecordNotFound
    flash.alert = t('errors.messages.dossier_not_found')
    redirect_to users_dossiers_path
  end
end

app/controllers/users/recapitulatif_controller.rb
class Users::RecapitulatifController < UsersController
  before_action only: [:show] do
    authorized_routes? self.class
  end

  def show
    create_dossier_facade
  end

  def initiate
    create_dossier_facade

    @facade.dossier.next_step! 'user', 'initiate'
    flash.notice = 'Dossier soumis avec succès.'

    redirect_to users_dossier_recapitulatif_path
  end

  def submit
    create_dossier_facade

    @facade.dossier.submit!
    flash.notice = 'Dossier déposé avec succès.'

    redirect_to users_dossier_recapitulatif_path
  end

  def self.route_authorization
    {
      states: %i[initiated replied updated validated received submitted without_continuation closed refused]
    }
  end

  private

  def create_dossier_facade
    @facade = DossierFacades.new current_user_dossier.id, current_user.email
  rescue ActiveRecord::RecordNotFound
    flash.alert = t('errors.messages.dossier_not_found')
    redirect_to root_path
  end
end

app/views/users/dossiers/_list.html.haml
- unless smart_listing.empty?
  %table#dossiers_list.table
    %thead
      %tr
        %th#sort-id.col-md-1.col-lg-1.col-sm-1.col-xs-1= smart_listing.sortable 'Numéro', 'id'
        %th#sort-libelle.col-md-5.col-sm-5.col-xs-5.col-lg-5= smart_listing.sortable 'Procédure', 'procedure.libelle'
        %th#sort-state.col-md-2.col-sm-2.col-xs-2.col-lg-2= smart_listing.sortable 'État', 'state'
        %th#sort-updated.col-md-2.col-sm-2.col-xs-2.col-lg-2= smart_listing.sortable 'Date de mise à jour', 'updated_at'
        - if @liste == "brouillon"
          %th.col-md-2.col-sm-2.col-xs-2.col-lg-2= 'Action'
    - @dossiers.each do |dossier|
      - if dossier.kind_of? Invite
        - invite = dossier
        - dossier = invite.dossier.decorate
      - else
        - dossier = dossier.decorate

      - dossier_url = users_dossiers_invite_path(id: invite.id) unless invite.nil?
      - if invite.nil?
        - dossier_url = users_dossier_recapitulatif_path(dossier) unless dossier.brouillon?
        - dossier_url = users_dossier_description_path(dossier) if dossier.brouillon?

      %tr{id: "tr_dossier_#{dossier.id}", 'data-dossier_url' => dossier_url}
        %td.center
          = dossier.id
        %td
          = dossier.procedure.libelle

        %td{id: "dossier_#{dossier.id}_state"}= dossier.display_state
        %td= dossier.last_update
        %td= link_to('X', url_for(controller: 'dossiers', action: :destroy, id: dossier.id), 'data-method' => :delete, class: 'btn-sm btn-danger') if @liste == "brouillon"

  = smart_listing.paginate
  = smart_listing.pagination_per_page_links
  %br

- else
  %h4.center
    Aucun dossier

app/views/users/dossiers/_state_description.html.haml
#state_description.row{style:'width: 55%; margin-left: auto; margin-right: auto'}
  .panel.panel-info
    .panel-body.center
      .row
        .col-md-1.col-lg-1.col-sm-1.col-xs-1
          .fa.fa-info-circle.text-info{style:'font-size: 2em; margin-top: 20%'}
        .col-md-11.col-sm-11.col-xs-11.col-lg-11
          - if dossiers_list_facade.liste == 'brouillon'
            Les dossiers présents dans cette liste
            %b
              n'ont pas encore été soumis aux services instructeurs.
            Ils ne sont visibles que par vous.
          - elsif dossiers_list_facade.liste == 'nouveaux'
            Les dossiers présents dans cette liste
            %b
              n'ont pas encore été ouverts
            par les services instructeurs. Une notification vous sera envoyée quand votre demande aura été étudiée.
          - elsif dossiers_list_facade.liste == 'a_traiter'
            Les dossiers présents dans cette liste sont
            %b
              visibles par les services instructeurs.
            %br
            Ces dossiers ne sont pas encore figés et peuvent être modifiés à souhait.
          - elsif dossiers_list_facade.liste == 'en_attente'
            Les dossiers présents dans cette liste sont
            %b
              en cours de relecture par les services instructeurs.
            Il reviendra vers vous si des informations ou documents sont manquants pour le futur examen de votre dossier.
          - elsif dossiers_list_facade.liste == 'valides'
            Les dossiers présents dans cette liste ont été
            %b
              relus et considérés comme complets
            pour examen par les services instructeurs. Ceux-ci ne peuvent maintenant plus être modifiés. Il faut que vous procédiez à leur dépôt afin qu'une décision finale soit rendue.
          - elsif dossiers_list_facade.liste == 'en_instruction'
            Les dossiers présents dans cette liste sont
            %b
              en cours de réception
            ou
            %b
              en cours d'examen
            par les services instructeurs. Une notification vous sera envoyée une fois qu'une décision aura été rendue.
          - elsif dossiers_list_facade.liste == 'termine'
            Les dossiers présents dans cette liste sont ceux qui ont été instruits et pour lesquels
            %b
              une décision finale a été rendue.
            Ils peuvent posséder trois états différents : Accepté, Refusé ou Sans Suite.
          - elsif dossiers_list_facade.liste == 'invite'
            Les dossiers présents dans cette liste sont ceux
            %b
              auxquels vous avez été invités
            à participer afin d'émettre un avis ou de fournir des documents complémentaires.

app/views/users/dossiers/index.html.haml
#users_index
  .default_data_block.default_visible
    %div.row.show-block#new_dossiers
      %div.header
        %div.col-lg-10.col-md-10.col-sm-10.col-xs-10.title
          %div.carret-right
          %div.carret-down
          Dossiers
        %div.col-lg-2.col-md-2.col-sm-2.col-xs-2.count
          -#0
          -#dossiers
      %div.body
        = smart_listing_render :dossiers

app/views/users/dossiers/index.js.erb
<%= smart_listing_update :dossiers %>
link_init();

app/views/users/dossiers/show.html.haml
= render partial:  '/dossiers/show'